image: fedora:31

stages:
  - Web Testes

test:
  stage: Web Testes
  before_script:
    # Instala pacotes necessários
    - dnf install -y Xvfb wget unzip python3 python3-pip mesa-libGL-devel libXcomposite libXcursor libXrandr libXi libXtst libXrender alsa-lib atk libXdamage gtk3
    # Baixa e instala o ChromeDriver
    - |
      CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+') && \
      CHROMEDRIVER_VERSION=$(echo $CHROME_VERSION | awk -F. '{print $1"."$2"."$3}') && \
      echo "Downloading ChromeDriver version: $CHROMEDRIVER_VERSION" && \
      wget -N https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip && \
      unzip chromedriver_linux64.zip -d /usr/bin/ && \
      rm chromedriver_linux64.zip && \
      chmod +x /usr/bin/chromedriver
    # Verifica se o ChromeDriver foi instalado corretamente
    - ls -l /usr/bin/chromedriver
  script:
    # Inicializa o Xvfb
    - Xvfb :99 -screen 0 1920x1080x24 &
    - export DISPLAY=:99
    - sleep 2  # Aguarda para garantir que o Xvfb esteja inicializado
    # Executa os testes
    - robot -d ./results -v BROWSER:headlesschrome tests/tests.robot
  artifacts:
    paths:
      - results/*.xml
      - results/*.html
  only:
    - main
